ALTER TYPE "public"."bank_account_type" ADD VALUE 'REGULAR_AGENCY_DSWD_FOV_REFUNDS' BEFORE 'FOREIGN_ASSISTED_LBP_MDS_KALAHI';--> statement-breakpoint
ALTER TYPE "public"."bank_account_type" ADD VALUE 'REGULAR_AGENCY_DSWD_CO_DEPOSITORY' BEFORE 'FOREIGN_ASSISTED_LBP_MDS_KALAHI';--> statement-breakpoint
ALTER TYPE "public"."bank_account_type" ADD VALUE 'FOREIGN_ASSISTED_LBP_MDS_PMNP' BEFORE 'SPECIAL_LOCALLY_FUNDED_DSWD_FO5_BCDA';--> statement-breakpoint
ALTER TYPE "public"."bank_account_type" ADD VALUE 'FOREIGN_ASSISTED_LBP_MDS_REGULAR' BEFORE 'SPECIAL_LOCALLY_FUNDED_DSWD_FO5_BCDA';--> statement-breakpoint
ALTER TYPE "public"."bank_account_type" ADD VALUE 'FOREIGN_ASSISTED_LBP_DSWD_BFIRST' BEFORE 'SPECIAL_LOCALLY_FUNDED_DSWD_FO5_BCDA';