DROP TYPE IF EXISTS "public"."transaction_type";--> statement-breakpoint
CREATE TYPE "public"."transaction_type" AS ENUM('BANK_CHARGES_SERVICE_FEES', 'BONUSES_AND_OTHER_ALLOWANCES', 'CASH_ADVANCE_SPECIAL_DISBURSING_OFFICER', 'CASH_ADVANCE_TRAVELING_EXPENSES', 'COST_OF_SERVICES_MOA_JOB_ORDER', 'DBM_PROCUREMENT_SERVICE_TRANSACTIONS', 'EXTRAORDINARY_AND_MISCELLANEOUS_EXPENSES', 'FIDELITY_BONDS', 'FINANCIAL_ASSISTANCE', 'FUND_TRANSFERS_TO_IMPLEMENTING_AGENCIES', 'HONORARIUM', 'NFA_TRANSACTIONS', 'OTHER_CASH_ASSISTANCE', 'OVERTIME_SERVICES', 'PETTY_CASH_FUND_INITIAL', 'PROCUREMENT_TRANSACTIONS', 'REFUND_OF_DEPOSITS', 'REFUND_OF_OVERPAYMENT_OF_EXPENSES', 'REGISTRATION_FEES', 'REIMBURSEMENT_OTHER_EXPENSES', 'REIMBURSEMENT_TRAVELING_EXPENSES', 'REMITTANCES', 'REPLACEMENT_OF_CANCELLED_CHECKS', 'REPLENISHMENT_OTHERS', 'REPLENISHMENT_PETTY_CASH_FUND', 'REQUEST_FOR_FUND_RELEASE', 'SALARIES_AND_WAGES', 'SEA_K_CASH_ASSISTANCE', 'TAX_REFUND', 'TAXES_DUTIES_LICENSES_AND_INSURANCE_PREMIUMS', 'UTILITIES', 'PURCHASE_OF_ACCOUNTABLE_FORMS');--> statement-breakpoint
CREATE TABLE "earmarks" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"earmark_code" varchar(150) NOT NULL,
	"fund_cluster" "fund_cluster" NOT NULL,
	"transaction_type" "transaction_type" NOT NULL,
	"date" timestamp NOT NULL,
	"particulars" text NOT NULL,
	"status" "status" NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "earmarks_earmark_code_unique" UNIQUE("earmark_code")
);
