services:
  empowerex-fsds-api:
    image: 619071352095.dkr.ecr.ap-southeast-1.amazonaws.com/empowerx-fsds
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: sh -c "/app/deployment/migration.sh && node dist/src/main.js"
