import { InferSelectModel, InferInsertModel } from 'drizzle-orm';
import { pgTable, uuid, timestamp, text, varchar, pgEnum } from 'drizzle-orm/pg-core';

export enum TransactionType {
  BANK_CHARGES_SERVICE_FEES = 'BANK_CHARGES_SERVICE_FEES',
  BONUSES_AND_OTHER_ALLOWANCES = 'BONUSES_AND_OTHER_ALLOWANCES',
  CASH_ADVANCE_SPECIAL_DISBURSING_OFFICER = 'CASH_ADVANCE_SPECIAL_DISBURSING_OFFICER',
  CASH_ADVANCE_TRAVELING_EXPENSES = 'CASH_ADVANCE_TRAVELING_EXPENSES',
  COST_OF_SERVICES_MOA_JOB_ORDER = 'COST_OF_SERVICES_MOA_JOB_ORDER',
  DBM_PROCUREMENT_SERVICE_TRANSACTIONS = 'DBM_PROCUREMENT_SERVICE_TRANSACTIONS',
  EXTRAORDINARY_AND_MISCELLANEOUS_EXPENSES = 'EXTRAORDINARY_AND_MISCELLANEOUS_EXPENSES',
  FIDELITY_BONDS = 'FIDELITY_BONDS',
  FINANCIAL_ASSISTANCE = 'FINANCIAL_ASSISTANCE',
  FUND_TRANSFERS_TO_IMPLEMENTING_AGENCIES = 'FUND_TRANSFERS_TO_IMPLEMENTING_AGENCIES',
  HONORARIUM = 'HONORARIUM',
  NFA_TRANSACTIONS = 'NFA_TRANSACTIONS',
  OTHER_CASH_ASSISTANCE = 'OTHER_CASH_ASSISTANCE',
  OVERTIME_SERVICES = 'OVERTIME_SERVICES',
  PETTY_CASH_FUND_INITIAL = 'PETTY_CASH_FUND_INITIAL',
  PROCUREMENT_TRANSACTIONS = 'PROCUREMENT_TRANSACTIONS',
  REFUND_OF_DEPOSITS = 'REFUND_OF_DEPOSITS',
  REFUND_OF_OVERPAYMENT_OF_EXPENSES = 'REFUND_OF_OVERPAYMENT_OF_EXPENSES',
  REGISTRATION_FEES = 'REGISTRATION_FEES',
  REIMBURSEMENT_OTHER_EXPENSES = 'REIMBURSEMENT_OTHER_EXPENSES',
  REIMBURSEMENT_TRAVELING_EXPENSES = 'REIMBURSEMENT_TRAVELING_EXPENSES',
  REMITTANCES = 'REMITTANCES',
  REPLACEMENT_OF_CANCELLED_CHECKS = 'REPLACEMENT_OF_CANCELLED_CHECKS',
  REPLENISHMENT_OTHERS = 'REPLENISHMENT_OTHERS',
  REPLENISHMENT_PETTY_CASH_FUND = 'REPLENISHMENT_PETTY_CASH_FUND',
  REQUEST_FOR_FUND_RELEASE = 'REQUEST_FOR_FUND_RELEASE',
  SALARIES_AND_WAGES = 'SALARIES_AND_WAGES',
  SEA_K_CASH_ASSISTANCE = 'SEA_K_CASH_ASSISTANCE',
  TAX_REFUND = 'TAX_REFUND',
  TAXES_DUTIES_LICENSES_AND_INSURANCE_PREMIUMS = 'TAXES_DUTIES_LICENSES_AND_INSURANCE_PREMIUMS',
  UTILITIES = 'UTILITIES',
  PURCHASE_OF_ACCOUNTABLE_FORMS = 'PURCHASE_OF_ACCOUNTABLE_FORMS',
}

export const transactionTypeEnum = pgEnum('transaction_type', [
  TransactionType.BANK_CHARGES_SERVICE_FEES,
  TransactionType.BONUSES_AND_OTHER_ALLOWANCES,
  TransactionType.CASH_ADVANCE_SPECIAL_DISBURSING_OFFICER,
  TransactionType.CASH_ADVANCE_TRAVELING_EXPENSES,
  TransactionType.COST_OF_SERVICES_MOA_JOB_ORDER,
  TransactionType.DBM_PROCUREMENT_SERVICE_TRANSACTIONS,
  TransactionType.EXTRAORDINARY_AND_MISCELLANEOUS_EXPENSES,
  TransactionType.FIDELITY_BONDS,
  TransactionType.FINANCIAL_ASSISTANCE,
  TransactionType.FUND_TRANSFERS_TO_IMPLEMENTING_AGENCIES,
  TransactionType.HONORARIUM,
  TransactionType.NFA_TRANSACTIONS,
  TransactionType.OTHER_CASH_ASSISTANCE,
  TransactionType.OVERTIME_SERVICES,
  TransactionType.PETTY_CASH_FUND_INITIAL,
  TransactionType.PROCUREMENT_TRANSACTIONS,
  TransactionType.REFUND_OF_DEPOSITS,
  TransactionType.REFUND_OF_OVERPAYMENT_OF_EXPENSES,
  TransactionType.REGISTRATION_FEES,
  TransactionType.REIMBURSEMENT_OTHER_EXPENSES,
  TransactionType.REIMBURSEMENT_TRAVELING_EXPENSES,
  TransactionType.REMITTANCES,
  TransactionType.REPLACEMENT_OF_CANCELLED_CHECKS,
  TransactionType.REPLENISHMENT_OTHERS,
  TransactionType.REPLENISHMENT_PETTY_CASH_FUND,
  TransactionType.REQUEST_FOR_FUND_RELEASE,
  TransactionType.SALARIES_AND_WAGES,
  TransactionType.SEA_K_CASH_ASSISTANCE,
  TransactionType.TAX_REFUND,
  TransactionType.TAXES_DUTIES_LICENSES_AND_INSURANCE_PREMIUMS,
  TransactionType.UTILITIES,
  TransactionType.PURCHASE_OF_ACCOUNTABLE_FORMS,
]);

export enum EarmarksFundCluster {
  REGULAR_AGENCY_FUND = '01',
  FOREIGN_ASSISTED_PROJECTS_FUND = '02',
  SPECIAL_ACCOUNT_LOCALLY_FUNDED_DOMESTIC_GRANTS_FUND = '03',
  SPECIAL_ACCOUNT_FOREIGN_ASSISTED_FOREIGN_GRANTS_FUND = '04',
  INTERNALLY_GENERATED_FUNDS = '05',
  BUSINESS_RELATED_FUNDS = '06',
  TRUST_RECEIPTS = '07',
}

export const fundClusterEnum = pgEnum('fund_cluster', [
  EarmarksFundCluster.REGULAR_AGENCY_FUND,
  EarmarksFundCluster.FOREIGN_ASSISTED_PROJECTS_FUND,
  EarmarksFundCluster.SPECIAL_ACCOUNT_LOCALLY_FUNDED_DOMESTIC_GRANTS_FUND,
  EarmarksFundCluster.SPECIAL_ACCOUNT_FOREIGN_ASSISTED_FOREIGN_GRANTS_FUND,
  EarmarksFundCluster.INTERNALLY_GENERATED_FUNDS,
  EarmarksFundCluster.BUSINESS_RELATED_FUNDS,
  EarmarksFundCluster.TRUST_RECEIPTS,
]);

export enum EarmarkStatus {
  DRAFT = 'DRAFT',
  FOR_TRIAGE = 'FOR_TRIAGE',
  FOR_PROCESSING = 'FOR_PROCESSING',
  FOR_PEER_REVIEW = 'FOR_PEER_REVIEW',
  FOR_FINALIZATION = 'FOR_FINALIZATION',
  REQUEST_FINALIZED = 'REQUEST_FINALIZED',
  REQUEST_REJECTED = 'REQUEST_REJECTED',
  REQUEST_FOR_REVIEW = 'REQUEST_FOR_REVIEW',
  FOR_APPROVAL = 'FOR_APPROVAL',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export const earmarkStatusEnum = pgEnum('status', [
  EarmarkStatus.DRAFT,
  EarmarkStatus.FOR_TRIAGE,
  EarmarkStatus.FOR_PROCESSING,
  EarmarkStatus.FOR_PEER_REVIEW,
  EarmarkStatus.FOR_FINALIZATION,
  EarmarkStatus.REQUEST_FINALIZED,
  EarmarkStatus.REQUEST_REJECTED,
  EarmarkStatus.REQUEST_FOR_REVIEW,
  EarmarkStatus.FOR_APPROVAL,
  EarmarkStatus.APPROVED,
  EarmarkStatus.REJECTED,
]);

export const earmarks = pgTable('earmarks', {
  id: uuid('id').primaryKey().defaultRandom(),
  user_id: uuid('user_id').notNull(),
  earmark_code: varchar('earmark_code', { length: 150 }).unique().notNull(),

  fund_cluster: fundClusterEnum('fund_cluster').notNull(),
  transaction_type: transactionTypeEnum('transaction_type').notNull(),
  date: timestamp('date').notNull(),
  particulars: text('particulars').notNull(),

  status: earmarkStatusEnum('status').notNull(),
  workflow_id: uuid('workflow_id'),
  created_at: timestamp('created_at').defaultNow().notNull(),
  updated_at: timestamp('updated_at')
    .defaultNow()
    .notNull()
    .$onUpdate(() => new Date()),
});

export type Earmark = InferSelectModel<typeof earmarks>;
export type NewEarmark = InferInsertModel<typeof earmarks>;
