name: CI/CD - Build, Push to ECR, Deploy
on:
  push:
    branches:
      - dev
      - staging
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SERVICE_NAME: ${{ secrets.SERVICE_NAME }} # Add this to your repository secrets e.g. "my-service"
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }} # Add this to your repository secrets e,g. "123456789012"
      AWS_REGION: ${{ secrets.AWS_REGION }} # Add this to your repository secrets e.g. "us-east-1"
      ASG_NAME: ${{ secrets.ASG_NAME }} # Add this to your repository secrets e.g "my-asg"
    steps:
      - uses: actions/checkout@v3

      - name: Set Environment Variables
        run: |
          if [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            echo "ENVIRONMENT=prod" >> $GITHUB_ENV
            echo "ENV_TAG=prod-latest" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF_NAME}" == "dev" ]]; then
            echo "ENVIRONMENT=dev" >> $GITHUB_ENV
            echo "ENV_TAG=dev-latest" >> $GITHUB_ENV
          else
            echo "ENVIRONMENT=staging" >> $GITHUB_ENV
            echo "ENV_TAG=staging-latest" >> $GITHUB_ENV
          fi

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login \
            --username AWS \
            --password-stdin ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build Docker Image
        run: docker build -t ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.SERVICE_NAME }}:${{ env.ENV_TAG }} .
        env:
          ENV_TAG: ${{ env.ENV_TAG }}

      - name: Generate docker-compose.yml
        run: |
          cat > docker-compose.yml <<EOL
          services:
            app:
              image: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.SERVICE_NAME }}:${{ env.ENV_TAG }}
              container_name: ${{ env.SERVICE_NAME }}-api
              ports:
                - "80:3000"
          EOL
        env:
          ENV_TAG: ${{ env.ENV_TAG }}

      - name: Generate .env from GitHub Secret
        run: echo "${{ secrets.CLEAN_ENV }}" > .env

      - name: Push Image
        run: docker push ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.SERVICE_NAME }}:${{ env.ENV_TAG }}

        env:
          ENV_TAG: ${{ env.ENV_TAG }}

      - name: Upload docker-compose to S3
        run: |

          S3_PATH="s3://s3-compose/${SERVICE_NAME}/${ENV_TAG}/docker-compose.yml"
          S3_ENV_PATH="s3://s3-compose/${SERVICE_NAME}/${ENV_TAG}/.env"

          echo "Uploading docker-compose.yml to $S3_PATH"

          # Upload
          aws s3 cp .env $S3_ENV_PATH --region $AWS_REGION
          aws s3 cp docker-compose.yml $S3_PATH --region $AWS_REGION
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SERVICE_NAME: ${{ env.SERVICE_NAME }}
          ENV_TAG: ${{ env.ENV_TAG }}
      - name: Trigger Instance Refresh
        run: |
          aws autoscaling start-instance-refresh \
            --auto-scaling-group-name ${{ secrets.ASG_NAME }} \
            --region ${{ env.AWS_REGION }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ASG_NAME: ${{ secrets.ASG_NAME }}
